application: scoutscr
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: Logos/Scouts-CR.ico
  upload: favicon\.ico

- url: /.*
  script: index.php